# helm repo add jboss-eap https://jbossas.github.io/eap-charts/
# helm install my-release -f values.yaml jboss-eap/eap8 --namespace eap7--1999
# helm uninstall my-release --namespace eap7--1999
build:
  uri: "https://github.com/tommaso-borgato/eap-rhsso-saml-sso-example.git"
  ref: "saml-feature-pack"
  mode: s2i
  env:
    - name: "MAVEN_MIRROR_URL"
      value: "http://repository.eapqe.psi.redhat.com:8081/artifactory/all/"
    - name: "MAVEN_ARGS_APPEND"
      value: " -Denforcer.skip=true -Dversion.war.maven.plugin=3.3.2"
#    - name: "SSO_SAML_LOGOUT_PAGE"
#      value: "/index.jsp"
#    - name: "SSO_SAML_VALIDATE_SIGNATURE"
#      value: "false"
#    - name: "SSO_DISABLE_SSL_CERTIFICATE_VALIDATION"
#      value: "true"
#    - name: "SSO_REALM"
#      value: "saml-basic-auth"
#    - name: "SSO_URL"
#      value: https://keycloak-eap7--1999.apps.tborgato-vnah.eapqe.psi.redhat.com/auth
#    - name: "SSO_USERNAME"
#      value: "client"
#    - name: "SSO_PASSWORD"
#      value: "creator"
deploy:
  replicas: 1
  env:
    # these are needed to configure file keycloak-saml.xml in the deployment
    - name: "SSO_REALM"
      value: "saml-basic-auth"
    - name: "SSO_URL"
      value: https://keycloak-eap7--1999.apps.tborgato-vnah.eapqe.psi.redhat.com/auth
      # value: "https://secure-sso-app-tborgato0.apps.tborgato-vnah.eapqe.psi.redhat.com/auth"
    - name: "SSO_USERNAME"
      value: "client"
    - name: "SSO_PASSWORD"
      value: "creator"
    #- name: "SSO_SAML_KEYSTORE_SECRET"
    #  value: "sso-saml-secret"
    - name: "SSO_SAML_KEYSTORE"
      value: "keystore"
    - name: "SSO_SAML_CERTIFICATE_NAME"
      value: "keyAlias"
    - name: "SSO_SAML_KEYSTORE_PASSWORD"
      value: "password"
    - name: "SSO_SAML_KEYSTORE_DIR"
      value: "/etc/sso-saml-secret-volume"
    - name: "SSO_SAML_LOGOUT_PAGE"
      value: "/index.jsp"
    - name: "SSO_SAML_VALIDATE_SIGNATURE"
      value: "false"
    - name: "SSO_DISABLE_SSL_CERTIFICATE_VALIDATION"
      value: "true"
  volumeMounts:
    - mountPath: "/etc/sso-saml-secret-volume"
      name: "sso-saml-keystore-volume"
      readOnly: true
  volumes:
    - name: "sso-saml-keystore-volume"
      secret:
        secretName: "sso-saml-secret"