# helm install my-release -f ./values-bootable.yaml ./wildfly-charts/charts/wildfly --namespace tborgato2
# helm uninstall my-release --namespace tborgato2
# helm upgrade my-release -f ./values-bootable.yaml ./wildfly-charts/charts/wildfly --namespace tborgato2
build:
  uri: "https://github.com/tommaso-borgato/eap-rhsso-saml-sso-example.git"
  ref: "saml-feature-pack-bootable"
  mode: bootable-jar
  env:
    - name: "MAVEN_MIRROR_URL"
      value: "http://repository.eapqe.psi.redhat.com:8081/artifactory/all/"
    - name: "MAVEN_ARGS_APPEND"
      value: " -Denforcer.skip=true -Dversion.war.maven.plugin=3.3.2"
    - name: MAVEN_ARGS_APPEND
      value: -P openshift
deploy:
  replicas: 1
  env:
    # these are needed to configure file keycloak-saml.xml in the deployment
    - name: "KEYCLOAK_SAML_ADAPTER_ENTITY_ID"
      value: "https://my-release-tborgato2.apps.tborgato-vnah.eapqe.psi.redhat.com/saml-app/"
    - name: "KEYCLOAK_SAML_ADAPTER_LOGOUT_PAGE"
      value: "https://my-release-tborgato2.apps.tborgato-vnah.eapqe.psi.redhat.com/saml-app/"
    - name: "KEYCLOAK_SAML_ADAPTER_BINDING_URL"
      value: "https://keycloak-tborgato2.apps.tborgato-vnah.eapqe.psi.redhat.com/auth/realms/basic-auth/protocol/saml"
    - name: "KEYCLOAK_SAML_ADAPTER_POST_BINDING_URL"
      value: "https://keycloak-tborgato2.apps.tborgato-vnah.eapqe.psi.redhat.com/auth/realms/basic-auth/protocol/saml"
    - name: "KEYCLOAK_SAML_ADAPTER_REDIRECT_BINDING_URL"
      value: "https://keycloak-tborgato2.apps.tborgato-vnah.eapqe.psi.redhat.com/auth/realms/basic-auth/protocol/saml"
