apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhsso-operator
spec:
  channel: stable
  config:
    env:
      - name: RELATED_IMAGE_RHSSO
        value: registry.redhat.io/rh-sso-7/sso76-openshift-rhel8:latest
      - name: PROFILE
        value: RHSSO
  name: rhsso-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
